# Include the unified build system
include ../../Makefile.template

# PROJECT CONFIGURATION
PROJECT_NAME = cto-bunq-proposal
OUTPUT_BASE = CTO-on-Demand-bunq-Proposal
LATEX_COMPILER = lualatex
BIB_TOOL = none
COMPILE_PASSES = 3
