#!/usr/bin/env python3
"""
Create a new LaTeX project from a template.

Usage:
    python create-project.py <template> <project-name> [--spec <spec-file>]
    python create-project.py tech-spec api-design
    python create-project.py research-paper thesis --spec thesis-spec.yml
"""

import argparse
import os
import sys
import yaml
from datetime import datetime
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent.parent
LATEX_DIR = REPO_ROOT / "documents" / "latex"
TEMPLATES_DIR = LATEX_DIR / "templates"
PROJECTS_DIR = LATEX_DIR / "projects"
REGISTRY_FILE = TEMPLATES_DIR / "registry.yml"


def load_registry():
    """Load the template registry."""
    if not REGISTRY_FILE.exists():
        print(f"Error: Registry file not found: {REGISTRY_FILE}")
        sys.exit(1)

    with open(REGISTRY_FILE) as f:
        return yaml.safe_load(f)


def load_spec(spec_file: str) -> dict:
    """Load a document specification file."""
    spec_path = Path(spec_file)
    if not spec_path.exists():
        print(f"Error: Spec file not found: {spec_file}")
        sys.exit(1)

    with open(spec_path) as f:
        return yaml.safe_load(f)


def create_makefile(project_dir: Path, template_config: dict, project_name: str, output_base: str):
    """Create the project Makefile."""
    compiler = template_config.get("compiler", "pdflatex")
    bib_tool = template_config.get("bib_tool", "none")

    makefile_content = f'''# LaTeX Project Makefile
# Generated by /latex on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

# Include the unified build system
include ../../Makefile.template

# PROJECT CONFIGURATION
PROJECT_NAME = {project_name}
OUTPUT_BASE = {output_base}
LATEX_COMPILER = {compiler}
BIB_TOOL = {bib_tool}
COMPILE_PASSES = 3
'''

    makefile_path = project_dir / "Makefile"
    with open(makefile_path, "w") as f:
        f.write(makefile_content)

    print(f"  Created: Makefile")


def create_main_tex(project_dir: Path, template_config: dict, spec: dict):
    """Create the main.tex file."""
    packages = template_config.get("packages", [])
    sections = spec.get("sections", template_config.get("sections", []))
    document_class = template_config.get("document_class", "article")
    compiler = template_config.get("compiler", "pdflatex")

    # Build package includes
    package_lines = []
    for pkg in packages:
        package_lines.append(f"\\usepackage{{{pkg}}}")

    # Build section inputs
    section_lines = []
    for section in sections:
        section_name = section if isinstance(section, str) else section.get("name", section)
        section_lines.append(f"\\input{{sections/{section_name}}}")

    # Document metadata
    doc_info = spec.get("document", {})
    title = doc_info.get("title", "Document Title")
    author = doc_info.get("author", "Morgan K. Reed")
    date_str = doc_info.get("date", "auto")
    date_cmd = "\\today" if date_str == "auto" else date_str

    # Build main.tex
    main_tex = f'''% Main Document
% Generated by /latex on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
% Template: {spec.get("template", "custom")}

\\documentclass[12pt,letterpaper]{{{document_class}}}

% Essential packages
\\usepackage[utf8]{{inputenc}}
\\usepackage[T1]{{fontenc}}
\\usepackage{{amsmath,amssymb}}
\\usepackage{{graphicx}}
\\usepackage{{hyperref}}
\\usepackage[margin=1in]{{geometry}}

% Style packages
{chr(10).join(package_lines)}

% Document metadata
\\title{{{title}}}
\\author{{{author}}}
\\date{{{date_cmd}}}

\\begin{{document}}

\\maketitle
\\tableofcontents
\\newpage

% Document sections
{chr(10).join(section_lines)}

\\end{{document}}
'''

    src_dir = project_dir / "src"
    src_dir.mkdir(exist_ok=True)

    main_tex_path = src_dir / "main.tex"
    with open(main_tex_path, "w") as f:
        f.write(main_tex)

    print(f"  Created: src/main.tex")


def create_section_files(project_dir: Path, template_config: dict, spec: dict):
    """Create section files."""
    sections = spec.get("sections", template_config.get("sections", []))

    sections_dir = project_dir / "src" / "sections"
    sections_dir.mkdir(parents=True, exist_ok=True)

    for section in sections:
        if isinstance(section, str):
            section_name = section
            section_title = section.replace("_", " ").title()
            key_points = []
        else:
            section_name = section.get("name", "section")
            section_title = section.get("title", section_name.replace("_", " ").title())
            key_points = section.get("key_points", [])

        # Create section content
        section_content = f'''% {section_title}
% Section: {section_name}

\\section{{{section_title}}}

'''

        if key_points:
            section_content += "% Key points to cover:\n"
            for point in key_points:
                section_content += f"% - {point}\n"
            section_content += "\n"

        section_content += f"% TODO: Write content for {section_title}\n\n"

        section_file = sections_dir / f"{section_name}.tex"
        with open(section_file, "w") as f:
            f.write(section_content)

    print(f"  Created: src/sections/ ({len(sections)} files)")


def create_document_spec(project_dir: Path, template_name: str, template_config: dict, spec: dict):
    """Create the document-spec.yml file."""
    final_spec = {
        "document": spec.get("document", {
            "title": "Document Title",
            "author": "Morgan K. Reed",
            "date": "auto"
        }),
        "template": template_name,
        "project": spec.get("project", {
            "name": project_dir.name,
            "output_base": project_dir.name.replace("-", " ").title().replace(" ", "-"),
            "location": str(project_dir.relative_to(REPO_ROOT))
        }),
        "build": {
            "compiler": template_config.get("compiler", "pdflatex"),
            "bib_tool": template_config.get("bib_tool", "none"),
            "compile_passes": 3
        },
        "packages": template_config.get("packages", []),
        "sections": spec.get("sections", [
            {"name": s} for s in template_config.get("sections", [])
        ]),
        "requirements": spec.get("requirements", {}),
        "metadata": {
            "created": datetime.now().isoformat(),
            "template_version": "1.0",
            "estimated_pages": template_config.get("estimated_pages", "unknown")
        }
    }

    spec_path = project_dir / "document-spec.yml"
    with open(spec_path, "w") as f:
        f.write("# Document Specification\n")
        f.write(f"# Generated by /latex on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("# This file captures planning decisions for future reference\n\n")
        yaml.dump(final_spec, f, default_flow_style=False, sort_keys=False)

    print(f"  Created: document-spec.yml")


def create_version_file(project_dir: Path):
    """Create the .version file."""
    version_path = project_dir / ".version"
    with open(version_path, "w") as f:
        f.write("0.1.0")
    print(f"  Created: .version (0.1.0)")


def create_project(template_name: str, project_name: str, spec: dict = None):
    """Create a new LaTeX project from a template."""
    # Load registry
    registry = load_registry()
    templates = registry.get("templates", {})

    # Validate template
    if template_name not in templates:
        print(f"Error: Unknown template '{template_name}'")
        print(f"Available templates: {', '.join(templates.keys())}")
        sys.exit(1)

    template_config = templates[template_name]

    # Create project directory
    project_dir = PROJECTS_DIR / project_name
    if project_dir.exists():
        print(f"Error: Project already exists: {project_dir}")
        sys.exit(1)

    project_dir.mkdir(parents=True)
    print(f"\nCreating project: {project_name}")
    print(f"  Template: {template_config['name']}")
    print(f"  Location: {project_dir}")
    print()

    # Use spec or create default
    if spec is None:
        spec = {
            "document": {
                "title": project_name.replace("-", " ").title(),
                "author": "Morgan K. Reed",
                "date": "auto"
            },
            "template": template_name,
            "project": {
                "name": project_name,
                "output_base": project_name.replace("-", " ").title().replace(" ", "-")
            },
            "sections": template_config.get("sections", [])
        }

    # Create project files
    output_base = spec.get("project", {}).get("output_base", project_name.title().replace("-", " ").replace(" ", "-"))

    create_makefile(project_dir, template_config, project_name, output_base)
    create_main_tex(project_dir, template_config, spec)
    create_section_files(project_dir, template_config, spec)
    create_document_spec(project_dir, template_name, template_config, spec)
    create_version_file(project_dir)

    print()
    print("Project created successfully!")
    print()
    print("Next steps:")
    print(f"  cd {project_dir}")
    print("  make draft    # Quick test build")
    print("  make patch    # Build with version 0.1.1")
    print()

    return project_dir


def main():
    parser = argparse.ArgumentParser(
        description="Create a new LaTeX project from a template"
    )
    parser.add_argument("template", help="Template name (e.g., tech-spec, research-paper)")
    parser.add_argument("project_name", help="Project name (e.g., api-design)")
    parser.add_argument("--spec", "-s", help="Document specification file (YAML)")

    args = parser.parse_args()

    # Load spec if provided
    spec = None
    if args.spec:
        spec = load_spec(args.spec)

    create_project(args.template, args.project_name, spec)


if __name__ == "__main__":
    main()
